### ISSUE TITLE
Include kills other Jquery plugins

### ISSUE THREAD

**Issue by Basiczombie** [ludrao/django-tellme#11]
This is a really great app. The only issue I am having is that when I include the js_inc.html something in the plugin blocks all my other Jquery plugins. I have noticed in your code you include a copy of Jquery in the plugin itself in the {% block jquery %}. Could this be the issue?

**Comment by Basiczombie** [comment]
I removed this block of code from the source and the plugin works.

```
{#Extend with an empty block or replace with your version of jquery#}
{%  block jquery %}
    <script src="http://code.jquery.com/jquery-1.12.2.min.js"></script>
{% endblock %}
```

As Jquery is already a major include in many sites I do not think that you need to enforce the use of jquery 1.12.2 as we are already up to jquery 3. It works for us as we are already including jquery but it might be better to list jquery as a requirement in your impressive doc than an auto include in the code itself.

**Comment by ludrao** [comment]
Hi @Basiczombie, thx for the feedback. As you commented the JQuery include is inside a {% block %} exactly for the reason you mentioned: most site already have JQuery included.
This plugin leverage the Django feature that is to redefine template in your app so that you can customize third party plugins.
So the way to proceed is to create in *your main application* a template/tellme/js_inc.html. I think you can  either copy paste the original js_inc.html and remove the jquery block. Some more detailed information is avialble here https://code.djangoproject.com/wiki/ExtendingAdminTemplates and there: https://code.djangoproject.com/wiki/ExtendingTemplates

Let me know if that works for you, I'll then close that ticket if that is OK.

Note: the initial reason of letting a jquery include in the default template is to simplify and reduce steps to make a first test of the plugin (so you do not have to pull multiple part from different location): a turnkey solution.
