### ISSUE TITLE
Images defined with CSS background property are missing

### ISSUE THREAD

**Issue by bnisevic** [ludrao/django-tellme#13]
Images defined with CSS background property are missing in the screenshot. Look at the picture below. Any ideas why is this and how it can be fixed? On my localhost it works, but on remote sites it misses these images.
![screenshot-dev giivx site-2017-01-31-17-31-59](https://cloud.githubusercontent.com/assets/1433428/22474260/b791e304-e7db-11e6-9b89-8b688a4d4185.png)

**Comment by ludrao** [comment]
Hum that is intersting (I think I might have seen a similar prb, but it was minor so never investigated more). This is most likely related to html2canvas (external project). https://github.com/niklasvh/html2canvas. I would start to look in that direction (try to repoduce it only with html2canvas plugin).
What is weird thought is that it seems  to depend on the location of the host???

I do not have much time to investigate it myself, and I am not specifically a js expert either :). Though if you find the issue, please let me know so that I can update html2canvas plugin in this project.

**Comment by nicolas-saubi** [comment]
Hi Bnisevic,

does it occurs on local or remote img ? If remote it's maybe related to this :
https://github.com/ivoviz/feedback#proxy-string

**Comment by bnisevic** [comment]
Hi @ludrao and @nicolassaubi! Thanks for your replies!

Yes the issue is present on remote servers, one serves via http other one uses https. And on my localhost where I do development I don't see this issue. Also, these two images are served locally on the same nginx but with different subdomain. So, yes you could be right, crossorigin could be the issue. I will get back when I obtain more information. Thanks!

**Comment by bnisevic** [comment]
Yup, I can confirm this is crossorigin issue not related to django-tellme. I will close the issue. But you can mention something about this in your documentation.
